jhipster:
    security:
        client-authorization:
          token-service-id: uaa
          client-id: internal
          client-secret: internal

eureka:
    client:
        fetch-registry: true
